#!/bin/bash

THRIFT_VER=0.9.0

# Decompress.
cd $SMT_MC_ROOT/mc-tools/dbug
rm thrift-$THRIFT_VER -rf
rm install -rf
tar zxvf $APPS_DIR/sys/thrift-$THRIFT_VER.tar.gz

# Compile thrift.
cd thrift-$THRIFT_VER
patch -p1 < ../../thrift-pkg-config.patch
./configure --prefix=$PWD/install --without-php --without-ruby --without-python --without-erlang
# We can not add -j64 for make, since there is process races and the make would fail sometimes...
make && make install

# Compile dbug.
cd $SMT_MC_ROOT/mc-tools/dbug
./bootstrap.sh
mkdir build
cd build
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$SMT_MC_ROOT/mc-tools/dbug/thrift-$THRIFT_VER/install/lib/pkgconfig/
export PATH=$SMT_MC_ROOT/mc-tools/dbug/thrift-$THRIFT_VER/install/bin/:$PATH
../configure --prefix=$SMT_MC_ROOT/mc-tools/dbug/install
make -j64 && make install

