#!/bin/bash

THRIFT_VER=0.9.0
PROJ="xtern+dbug"

# Update src of dbug based on the new api.xml.
cd $SMT_MC_ROOT/mc-tools/dbug/src/scripts
chmod 777 dbug-gen.rb
./dbug-gen.rb

# Re-compile dbug.
cd $SMT_MC_ROOT/mc-tools/dbug
./bootstrap.sh
mkdir -p build-$PROJ
cd build-$PROJ
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$SMT_MC_ROOT/mc-tools/dbug/thrift-$THRIFT_VER/install/lib/pkgconfig/
export PATH=$PATH:$SMT_MC_ROOT/mc-tools/dbug/thrift-$THRIFT_VER/install/bin/
../configure --prefix=$SMT_MC_ROOT/mc-tools/dbug/install-$PROJ
make -j64 && make install

